import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  NAV_ROUTES
} from '../src/components/navigation.js';
import {
  PAGE_CONTRACT_SCHEMA_VERSION,
  PAGE_CONTRACTS_BY_HREF,
  READINESS_VOCABULARY,
  getPageContract,
  getPageContractCoverage
} from '../src/pageContracts.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, '..');
const outputPath = path.join(root, 'docs', 'page-contracts.md');
const sections = ['Workflow', 'Studies'];

function scopedRoutes() {
  return NAV_ROUTES.filter(route => sections.includes(route.section));
}

function formatInputs(items) {
  if (!items.length) return '- No project inputs are required.';
  return items.map(item => {
    const required = item.required ? 'required' : 'optional';
    return `- \`${item.key}\` (${item.kind}, ${required}): ${item.purpose}`;
  }).join('\n');
}

function formatOutputs(items) {
  return items.map(item => {
    const consumers = item.consumers.length ? ` Consumers: ${item.consumers.map(href => `\`${href}\``).join(', ')}.` : '';
    return `- \`${item.key}\` (${item.kind}): ${item.purpose}${consumers}`;
  }).join('\n');
}

function formatList(items) {
  if (!items.length) return '- None.';
  return items.map(item => `- ${item}`).join('\n');
}

function formatHrefList(items) {
  if (!items.length) return '- None.';
  return items.map(item => `- \`${item}\``).join('\n');
}

function renderContract(route, pageContract) {
  return [
    `#### ${route.label} (\`${route.href}\`)`,
    '',
    `- Section: ${route.section}`,
    `- Group: ${route.group || 'General'}`,
    `- Workflow step: ${pageContract.workflowStep || 'none'}`,
    '',
    '**Standalone Inputs**',
    formatList(pageContract.standaloneInputs),
    '',
    '**Project Inputs**',
    formatInputs(pageContract.projectInputs),
    '',
    '**Outputs**',
    formatOutputs(pageContract.outputs),
    '',
    '**Readiness**',
    `- Ready when: ${pageContract.readiness.readyWhen}`,
    `- Blockers: ${pageContract.readiness.blockers.join('; ')}`,
    '',
    '**Downstream Pages**',
    formatHrefList(pageContract.downstream),
    '',
    '**Notes**',
    formatList(pageContract.notes),
    ''
  ].join('\n');
}

export function renderPageContractsMarkdown() {
  const coverage = getPageContractCoverage(NAV_ROUTES);
  if (coverage.missing.length || coverage.extra.length) {
    throw new Error(`Page contract coverage mismatch. Missing: ${coverage.missing.join(', ') || 'none'}; Extra: ${coverage.extra.join(', ') || 'none'}`);
  }

  const lines = [
    '# Workflow and Studies Page Contracts',
    '',
    '<!-- Generated by scripts/generatePageContractsDocs.mjs. Do not edit by hand. -->',
    '',
    `Schema version: ${PAGE_CONTRACT_SCHEMA_VERSION}`,
    '',
    'This document defines handoff-level inputs, outputs, readiness rules, and downstream consumers for every page in the Workflow and Studies navigation dropdowns.',
    '',
    `Standard readiness vocabulary: ${READINESS_VOCABULARY.ready}, ${READINESS_VOCABULARY.missingInputs}, ${READINESS_VOCABULARY.downstreamHandoff}.`,
    '',
    `Coverage: ${coverage.totalContracts} contracts for ${coverage.totalRoutes} navigation routes.`,
    ''
  ];

  for (const section of sections) {
    lines.push(`## ${section}`, '');
    const routes = scopedRoutes().filter(route => route.section === section);
    const groups = [...new Set(routes.map(route => route.group || 'General'))];
    for (const group of groups) {
      lines.push(`### ${group}`, '');
      for (const route of routes.filter(item => (item.group || 'General') === group)) {
        const pageContract = getPageContract(route.href);
        lines.push(renderContract(route, pageContract));
      }
    }
  }

  return `${lines.join('\n').replace(/\n{3,}/g, '\n\n').trim()}\n`;
}

async function main() {
  const markdown = renderPageContractsMarkdown();
  if (process.argv.includes('--check')) {
    const current = await fs.readFile(outputPath, 'utf8').catch(() => '');
    if (current !== markdown) {
      throw new Error('docs/page-contracts.md is out of date. Run node scripts/generatePageContractsDocs.mjs.');
    }
    console.log('[page-contracts] docs/page-contracts.md is current.');
    return;
  }

  await fs.writeFile(outputPath, markdown);
  console.log(`[page-contracts] Wrote ${path.relative(root, outputPath)} with ${Object.keys(PAGE_CONTRACTS_BY_HREF).length} contracts.`);
}

if (path.resolve(process.argv[1] || '') === fileURLToPath(import.meta.url)) {
  main().catch(error => {
    console.error(error.message);
    process.exit(1);
  });
}
