export function createRoutingState() {
  return {
    manualTrays: [],
    cableList: [],
    trayData: [],
    latestRouteData: [],
    selectedRouteIndex: null,
    sharedFieldRoutes: [],
    trayCableMap: {},
    fieldSegmentCableMap: new Map(),
    updatedUtilData: [],
    utilizationOverloadFilter: false,
    finalTrays: [],
    highlightTraceIndex: null,
    ductbankData: null,
    ductbankTraceIndices: [],
    ductbankVisible: true,
    fieldConnectionsVisible: true,
    plotView: 'isometric',
    labelsVisible: true,
    conduitData: [],
    ductbanksWithoutConduits: [],
    includeDuctbankOutlines: false,
    geometryWarnings: { ductbanks: [], conduits: [] },
    heatmapEnabled: false,
    pullChecksEnabled: false,
    pullSetupsVisible: true,
    pullGroupAnalysis: null,
    pullGroupDecisions: {},
    expandedPullGroupIds: new Set(),
    routeViewer: null,
    routeViewerLoad: null,
    routeViewerFailed: false,
    sampleDataMode: false,
    largeFacilityTestMode: false
  };
}
