import { NAV_ROUTES } from './components/navigation.js';

export const PAGE_CONTRACT_SCHEMA_VERSION = 2;

const CONTRACT_SECTIONS = new Set(['Workflow', 'Studies']);

export const READINESS_VOCABULARY = Object.freeze({
  ready: 'Ready',
  missingInputs: 'Missing inputs',
  downstreamHandoff: 'Downstream handoff'
});

function projectInput(key, kind, required, purpose, options = {}) {
  const input = { key, kind, required: Boolean(required), purpose };
  if (options.audit) input.audit = options.audit;
  return input;
}

function output(key, kind, purpose, consumers = []) {
  return { key, kind, purpose, consumers };
}

function contract({
  workflowStep = null,
  standaloneInputs,
  projectInputs = [],
  outputs,
  readiness,
  downstream = [],
  notes = []
}) {
  return {
    workflowStep,
    standaloneInputs,
    projectInputs,
    outputs,
    readiness,
    downstream,
    notes
  };
}

function normalizeHref(href) {
  return String(href || '').split('/').pop();
}

function routeLabel(href) {
  const normalized = normalizeHref(href);
  const route = NAV_ROUTES.find(item => item.href === normalized);
  if (route?.label) return route.label;
  return normalized.replace(/\.html$/i, '').replace(/[-_]/g, ' ');
}

const equipment = projectInput('equipment', 'schedule', true, 'Equipment tags, ratings, locations, and physical metadata.');
const loads = projectInput('loadList', 'schedule', true, 'Load tags, source relationships, demand values, and operating metadata.');
const oneLine = projectInput('oneLineDiagram', 'model', true, 'One-line components, connections, sheets, layers, and linked schedule references.');
const panels = projectInput('panelSchedule', 'schedule', false, 'Panel and circuit records used for load, cable, and one-line handoffs.');
const cables = projectInput('cableSchedule', 'schedule', true, 'Cable tags, endpoints, conductor details, lengths, and raceway assignments.');
const trays = projectInput('traySchedule', 'schedule', true, 'Tray IDs, dimensions, fill limits, material, and route geometry.');
const conduits = projectInput('conduitSchedule', 'schedule', true, 'Conduit IDs, trade sizes, fill limits, material, and route geometry.');
const ductbanks = projectInput('ductbankSchedule', 'schedule', false, 'Ductbank segments, conduit groups, geometry, and underground routing metadata.');
const studies = projectInput('studyResults', 'study-result', false, 'Saved study results available for reports, cross-checks, and downstream studies.');
const designBasis = projectInput('settings.designBasis', 'setting', false, 'Project code basis, sizing defaults, routing defaults, and study prerequisites.', { audit: { expectRead: false, reason: 'Broad workflow context; many pages declare design basis as a readiness/handoff input even when the page does not directly read it.' } });
const designGates = projectInput('settings.designGateApprovals', 'setting', false, 'Review gate status used before deliverable release.');
const tccSettings = projectInput('settings.tccSettings', 'setting', false, 'Protective device selections, relay settings, chart options, and coordination context.');
const latestRouteResults = projectInput('settings.latestRouteResults', 'setting', false, 'Latest saved route batch generated by routing automation or Optimal Route.');
const approvals = projectInput('settings.studyApprovals', 'setting', false, 'Engineer review records for study outputs.');
const reportSnapshots = projectInput('settings.reportSnapshots', 'setting', false, 'Saved report package snapshots used by deliverable pages.');
const lifecyclePackages = projectInput('settings.lifecyclePackages', 'setting', false, 'Release package records and lifecycle package history.');
const scenarios = projectInput('settings.scenarios', 'setting', false, 'Scenario registry and active scenario selection.');
const oneLineReconcilePending = projectInput('settings.oneLineScheduleReconcilePending', 'setting', false, 'Flag indicating one-line schedule reconciliation is available.');
const equipmentFilterPresets = projectInput('settings.equipmentFilterPresets', 'setting', false, 'Saved equipment list filter presets.');
const mccLineupActiveId = projectInput('settings.mccLineupActiveId', 'setting', false, 'Active MCC lineup selection.');
const cableTagSettings = projectInput('settings.cableTagSettings', 'setting', false, 'Cable tag generation settings.');
const cableChangeLog = projectInput('settings.cableChangeLog', 'setting', false, 'Cable schedule change log entries.');
const ductbankPanZoom = projectInput('settings.ductbankPanZoom', 'setting', false, 'Ductbank canvas pan and zoom state.');
const ductbankSession = projectInput('settings.ductbankSession', 'setting', false, 'Ductbank page session state.');
const ductbankRouteData = projectInput('settings.ductbankRouteData', 'setting', false, 'Selected ductbank route handoff data.');
const trayFillData = projectInput('settings.trayFillData', 'setting', false, 'Selected tray fill handoff data.');
const conduitFillData = projectInput('settings.conduitFillData', 'setting', false, 'Selected conduit fill handoff data.');
const routeSession = projectInput('settings.ctrSession', 'setting', false, 'Optimal Route working session values.');
const routeResultsStudy = projectInput('studyResults.routeResults', 'study-result', false, 'Route result rows stored in study results by legacy workflows.');
const iec60287Study = projectInput('studyResults.iec60287', 'study-result', false, 'IEC 60287 result used as cable thermal context.');
const pvResult = projectInput('studyResults.pvResult', 'study-result', false, 'PV model result used by the IBR page.');
const bessResult = projectInput('studyResults.bessResult', 'study-result', false, 'BESS model result used by the IBR page.');
const faultResult = projectInput('studyResults.faultResult', 'study-result', false, 'IBR fault contribution result.');
const voltVarResult = projectInput('studyResults.voltVarResult', 'study-result', false, 'IBR volt-var result.');
const studyApprovalOutput = output('settings.studyApprovals', 'setting', 'Engineer approval records written by the shared study approval panel.', ['projectreport.html']);

const coreProjectInputs = [equipment, loads, oneLine, panels, cables, trays, conduits, ductbanks, studies, designBasis];
const racewayInputs = [cables, trays, conduits, ductbanks, designBasis];
const powerModelInputs = [equipment, loads, oneLine, cables, studies, tccSettings, designBasis];
const deliverableInputs = [equipment, loads, oneLine, panels, cables, trays, conduits, ductbanks, studies, latestRouteResults, designBasis, designGates, approvals];

const ready = (readyWhen, blockers) => ({ readyWhen, blockers });
const exportOnly = (purpose, consumers = []) => output('export-only', 'export', purpose, consumers);

export const PAGE_CONTRACTS_BY_HREF = {
  'workflowdashboard.html': contract({
    standaloneInputs: ['Manual project review, workflow navigation, and sample project loading.'],
    projectInputs: [...coreProjectInputs, approvals, reportSnapshots, lifecyclePackages, tccSettings, oneLineReconcilePending],
    outputs: [
      output('settings.designBasis', 'setting', 'Design basis wizard decisions and project defaults.', ['workflowdashboard.html', 'projectreport.html']),
      output('settings.designGateApprovals', 'setting', 'Design gate approvals and flagged review decisions.', ['workflowdashboard.html', 'projectreport.html']),
      output('settings.latestRouteResults', 'setting', 'Automation-seeded route results when the dashboard workflow runner creates routing output.', ['pullcards.html', 'spoolsheets.html', 'projectreport.html']),
      output('oneLineDiagram', 'model', 'Automation-seeded one-line model when workflow automation creates starter project data.', ['oneline.html']),
      output('cableSchedule', 'schedule', 'Automation-seeded cable schedule rows.', ['cableschedule.html', 'optimalRoute.html']),
      output('traySchedule', 'schedule', 'Automation-seeded tray schedule rows.', ['racewayschedule.html', 'optimalRoute.html']),
      output('conduitSchedule', 'schedule', 'Automation-seeded conduit schedule rows.', ['racewayschedule.html', 'optimalRoute.html']),
      output('ductbankSchedule', 'schedule', 'Automation-seeded ductbank schedule rows.', ['ductbankroute.html', 'optimalRoute.html']),
      output('settings.lifecyclePackages', 'setting', 'Lifecycle package records created from dashboard package actions.', ['projectreport.html']),
      output('settings.oneLineScheduleReconcilePending', 'setting', 'Workflow automation reconcile state for one-line and schedule handoff.', ['oneline.html'])
    ],
    readiness: ready('Dashboard is ready when it can summarize every workflow step and identify the next incomplete handoff.', ['Missing schedule data, unresolved review gates, pending studies, or no deliverables.']),
    downstream: ['equipmentlist.html', 'loadlist.html', 'oneline.html', 'cableschedule.html', 'racewayschedule.html', 'projectreport.html'],
    notes: ['This page aggregates workflow state instead of belonging to a single workflow step.']
  }),
  'scenarios.html': contract({
    standaloneInputs: ['Scenario names, imported project snapshots, and comparison selections.'],
    projectInputs: [...coreProjectInputs, scenarios],
    outputs: [
      exportOnly('Scenario comparison tables and exports.')
    ],
    readiness: ready('Ready when at least two named scenarios can be compared or a baseline scenario can be cloned.', ['Only one scenario exists or selected scenario data is empty.']),
    downstream: ['workflowdashboard.html', 'projectreport.html'],
    notes: ['Scenario storage is project workflow context, not a standalone engineering result.']
  }),
  'equipmentlist.html': contract({
    workflowStep: 'equipmentList',
    standaloneInputs: ['Manual equipment rows, starter records, imports, and bulk edit selections.'],
    projectInputs: [equipment, oneLine, equipmentFilterPresets, designBasis],
    outputs: [
      output('equipment', 'schedule', 'Major equipment register with tags, ratings, arrangements, dimensions, and locations.', ['equipmentarrangements.html', 'mcclineup.html', 'loadlist.html', 'oneline.html', 'equipmentevaluation.html']),
      output('settings.equipmentColumns', 'setting', 'Equipment table display configuration.', ['equipmentlist.html']),
      output('settings.equipmentFilterPresets', 'setting', 'Saved equipment filter presets.', ['equipmentlist.html'])
    ],
    readiness: ready('At least one meaningful equipment row exists.', ['No equipment tags or starter records have been added.']),
    downstream: ['equipmentarrangements.html', 'mcclineup.html', 'loadlist.html', 'oneline.html']
  }),
  'equipmentarrangements.html': contract({
    workflowStep: 'equipmentList',
    standaloneInputs: ['Arrangement canvas edits, block positions, imported layouts, and manual equipment dimensions.'],
    projectInputs: [equipment, projectInput('mccLineups', 'schedule', false, 'Lineup metadata used to preview MCC blocks.')],
    outputs: [
      output('equipment', 'schedule', 'Arrangement-driven equipment row updates.', ['equipmentlist.html']),
      output('settings.equipmentArrangements', 'setting', 'Named arrangement layouts and equipment block geometry.', ['equipmentlist.html', 'projectreport.html']),
      exportOnly('Arrangement drawings and layout reports.', ['projectreport.html'])
    ],
    readiness: ready('Ready when selected equipment has dimensions or placement data for layout review.', ['Equipment tags are missing or selected equipment lacks physical size/location metadata.']),
    downstream: ['equipmentlist.html', 'projectreport.html']
  }),
  'mcclineup.html': contract({
    workflowStep: 'equipmentList',
    standaloneInputs: ['Lineup names, bucket entries, starter metadata, and physical lineup dimensions.'],
    projectInputs: [equipment, mccLineupActiveId],
    outputs: [
      output('mccLineups', 'schedule', 'Persisted MCC lineup definitions and active lineup selection.', ['equipmentlist.html', 'equipmentarrangements.html', 'projectreport.html']),
      output('equipment', 'schedule', 'Optional synchronized MCC equipment rows.', ['equipmentlist.html', 'oneline.html']),
      output('settings.mccLineupActiveId', 'setting', 'Active MCC lineup selection.', ['mcclineup.html'])
    ],
    readiness: ready('Ready when at least one lineup contains identifiable sections or buckets.', ['No lineup exists or lineup entries are missing equipment tags.']),
    downstream: ['equipmentlist.html', 'equipmentarrangements.html', 'projectreport.html']
  }),
  'loadlist.html': contract({
    workflowStep: 'loadList',
    standaloneInputs: ['Manual load rows, imports, equipment source selections, and demand metadata.'],
    projectInputs: [equipment, panels, oneLine, designBasis],
    outputs: [
      output('loadList', 'schedule', 'Load schedule with source, demand, power factor, duty, and equipment links.', ['oneline.html', 'demandschedule.html', 'loadFlow.html', 'generatorsizing.html']),
      output('settings.loadListViewPreset', 'setting', 'Load list view and grouping preferences.', ['loadlist.html'])
    ],
    readiness: ready('At least one meaningful load row exists.', ['No load records exist or source relationships are not assigned for workflow handoff.']),
    downstream: ['oneline.html', 'demandschedule.html', 'cableschedule.html']
  }),
  'oneline.html': contract({
    workflowStep: 'oneLineDiagram',
    standaloneInputs: ['Manual diagram drawing, palette components, imported sample diagrams, and reconcile choices.'],
    projectInputs: [
      equipment, loads, panels, cables, trays, conduits, studies, tccSettings,
      projectInput('settings.manufacturerDefaults', 'setting', false, 'Manufacturer default selections for one-line component properties.'),
      projectInput('settings.oneLineDiagramFilterMode', 'setting', false, 'One-line component filter mode.'),
      projectInput('settings.diagramScale', 'setting', false, 'Diagram scale setting.'),
      projectInput('settings.diagramZoom', 'setting', false, 'Diagram zoom state.'),
      projectInput('settings.studySettings', 'setting', false, 'One-line embedded study settings.'),
      projectInput('settings.gridSize', 'setting', false, 'Diagram grid size.'),
      projectInput('settings.gridEnabled', 'setting', false, 'Diagram grid visibility.'),
      projectInput('settings.labelPrefixes', 'setting', false, 'One-line label prefix settings.'),
      projectInput('settings.labelCounters', 'setting', false, 'One-line label counter state.'),
      projectInput('settings.layersPanelOpen', 'setting', false, 'Layer panel open/closed state.'),
      projectInput('settings.orthogonalRouting', 'setting', false, 'Orthogonal connection routing preference.'),
      projectInput('settings.symbolStandard', 'setting', false, 'ANSI/IEC symbol standard selection.'),
      projectInput('settings.diagramTitleBlock', 'setting', false, 'One-line title block fields.'),
      projectInput('settings.diagramDatablockConfig', 'setting', false, 'One-line datablock display configuration.'),
      projectInput('settings.gistToken', 'setting', false, 'Gist import/export token setting.')
    ],
    outputs: [
      output('oneLineDiagram', 'model', 'One-line sheets, components, connections, layers, protection zones, and linked schedule refs.', ['loadFlow.html', 'shortCircuit.html', 'arcFlash.html', 'tcc.html', 'designrulechecker.html']),
      output('cableSchedule', 'schedule', 'Explicit reconcile-created or reconcile-updated cable rows.', ['cableschedule.html', 'optimalRoute.html']),
      output('loadList', 'schedule', 'Explicit reconcile-created or reconcile-updated load rows.', ['loadlist.html']),
      output('panelSchedule', 'schedule', 'Explicit reconcile-created or reconcile-updated panel rows.', ['panelschedule.html']),
      output('equipment', 'schedule', 'Explicit reconcile-created or reconcile-updated equipment rows.', ['equipmentlist.html']),
      output('traySchedule', 'schedule', 'Raceway records created from one-line route actions.', ['racewayschedule.html']),
      output('conduitSchedule', 'schedule', 'Conduit records created from one-line route actions.', ['racewayschedule.html']),
      output('studyResults', 'study-result', 'Embedded one-line study result container.', ['projectreport.html']),
      output('studyResults.loadFlow', 'study-result', 'Embedded load-flow result generated from one-line.', ['loadFlow.html', 'projectreport.html']),
      output('studyResults.shortCircuit', 'study-result', 'Embedded short-circuit result generated from one-line.', ['shortCircuit.html', 'projectreport.html']),
      output('studyResults.arcFlash', 'study-result', 'Embedded arc-flash result generated from one-line.', ['arcFlash.html', 'projectreport.html']),
      output('studyResults.harmonics', 'study-result', 'Embedded harmonics result generated from one-line.', ['harmonics.html', 'projectreport.html']),
      output('studyResults.motorStart', 'study-result', 'Embedded motor-start result generated from one-line.', ['motorStart.html', 'projectreport.html']),
      output('studyResults.reliability', 'study-result', 'Embedded reliability result generated from one-line.', ['reliability.html', 'projectreport.html']),
      output('studyResults.duty', 'study-result', 'Embedded equipment-duty result generated from one-line validation.', ['equipmentevaluation.html', 'projectreport.html']),
      output('settings.scenarios', 'setting', 'Active scenario selection restored during one-line project import.', ['scenarios.html']),
      output('settings.studySettings', 'setting', 'One-line embedded study settings.', ['oneline.html']),
      output('settings.diagramZoom', 'setting', 'Diagram zoom state.', ['oneline.html']),
      output('settings.labelCounters', 'setting', 'One-line label counter state.', ['oneline.html']),
      output('settings.labelPrefixes', 'setting', 'One-line label prefix settings.', ['oneline.html']),
      output('settings.manufacturerDefaults', 'setting', 'Manufacturer default selections for one-line component properties.', ['oneline.html']),
      output('settings.gridEnabled', 'setting', 'Diagram grid visibility.', ['oneline.html']),
      output('settings.diagramDatablockConfig', 'setting', 'One-line datablock display configuration.', ['oneline.html']),
      output('settings.diagramScale', 'setting', 'Diagram scale setting.', ['oneline.html']),
      output('settings.layersPanelOpen', 'setting', 'Layer panel open/closed state.', ['oneline.html']),
      output('settings.gridSize', 'setting', 'Diagram grid size.', ['oneline.html']),
      output('settings.oneLineDiagramFilterMode', 'setting', 'One-line component filter mode.', ['oneline.html']),
      output('settings.orthogonalRouting', 'setting', 'Orthogonal connection routing preference.', ['oneline.html']),
      output('settings.symbolStandard', 'setting', 'ANSI/IEC symbol standard selection.', ['oneline.html']),
      output('settings.diagramTitleBlock', 'setting', 'One-line title block fields.', ['oneline.html']),
      output('settings.gistToken', 'setting', 'Gist import/export token setting.', ['oneline.html']),
      output('settings.onelineTemplates', 'setting', 'Reusable one-line component templates saved with project settings.', ['oneline.html']),
      output('settings.oneLineScheduleReconcilePending', 'setting', 'Flag indicating that schedule reconciliation is available.', ['workflowdashboard.html'])
    ],
    readiness: ready('At least one one-line component exists and schedule reconciliation state is explicit.', ['Diagram is empty or schedule reconciliation issues remain unresolved.']),
    downstream: ['cableschedule.html', 'loadFlow.html', 'shortCircuit.html', 'arcFlash.html', 'tcc.html']
  }),
  'cableschedule.html': contract({
    workflowStep: 'cableSchedule',
    standaloneInputs: ['Manual cable rows, template selection, imports, inline edits, and report options.'],
    projectInputs: [equipment, loads, panels, oneLine, trays, conduits, ductbanks, cableTagSettings, cableChangeLog, designBasis],
    outputs: [
      output('cableSchedule', 'schedule', 'Cable rows with tags, endpoints, conductor details, length, and raceway assignments.', ['racewayschedule.html', 'cabletrayfill.html', 'conduitfill.html', 'optimalRoute.html', 'voltagedropstudy.html']),
      output('settings.cableTemplates', 'setting', 'User-maintained cable templates.', ['cableschedule.html']),
      output('settings.cableTagSettings', 'setting', 'Cable tag generation settings.', ['cableschedule.html']),
      output('settings.cableChangeLog', 'setting', 'Cable schedule change log entries.', ['cableschedule.html'])
    ],
    readiness: ready('Every workflow cable row has tag, from/to, conductor size, and length.', ['Missing tag, endpoints, conductor size, or length on one or more cable rows.']),
    downstream: ['racewayschedule.html', 'cabletrayfill.html', 'conduitfill.html', 'optimalRoute.html']
  }),
  'panelschedule.html': contract({
    workflowStep: 'cableSchedule',
    standaloneInputs: ['Panel definitions, circuit rows, breaker selections, connected loads, and cable tags.'],
    projectInputs: [equipment, loads, cables, designBasis],
    outputs: [
      output('panelSchedule', 'schedule', 'Panel metadata, circuit schedules, breaker assignments, and served load links.', ['loadlist.html', 'oneline.html', 'cableschedule.html']),
      output('loadList', 'schedule', 'Panel-driven load updates when circuit edits create or update served loads.', ['loadlist.html', 'demandschedule.html']),
      output('cableSchedule', 'schedule', 'Panel-driven cable references when circuit rows create cable links.', ['cableschedule.html']),
      output('equipment', 'schedule', 'Panel-driven equipment updates for synchronized panel records.', ['equipmentlist.html'])
    ],
    readiness: ready('Ready when panels have valid IDs and circuit rows are internally consistent.', ['Panel ID, voltage, circuit count, or connected load data is incomplete.']),
    downstream: ['loadlist.html', 'oneline.html', 'cableschedule.html']
  }),
  'racewayschedule.html': contract({
    workflowStep: 'racewaySchedule',
    standaloneInputs: ['Tray, conduit, ductbank, CAD import, geometry, and fill setup rows.'],
    projectInputs: [cables, designBasis],
    outputs: [
      output('traySchedule', 'schedule', 'Tray records with dimensions, material, capacity, and geometry.', ['cabletrayfill.html', 'optimalRoute.html', 'trayhardwarebom.html', 'windload.html']),
      output('conduitSchedule', 'schedule', 'Conduit records with trade size, material, capacity, and geometry.', ['conduitfill.html', 'ductbankroute.html', 'optimalRoute.html']),
      output('ductbankSchedule', 'schedule', 'Ductbank records and conduit grouping metadata.', ['ductbankroute.html', 'optimalRoute.html']),
      output('cableSchedule', 'schedule', 'Raceway assignment edits written back to cable rows.', ['cableschedule.html']),
      output('settings.trayFillData', 'setting', 'Selected tray fill handoff data.', ['cabletrayfill.html']),
      output('settings.conduitFillData', 'setting', 'Selected conduit fill handoff data.', ['conduitfill.html']),
      output('settings.ductbankSession', 'setting', 'Ductbank schedule handoff state.', ['ductbankroute.html'])
    ],
    readiness: ready('At least one tray, conduit, or ductbank record exists.', ['No routeable raceway records have been added.']),
    downstream: ['cabletrayfill.html', 'conduitfill.html', 'ductbankroute.html', 'optimalRoute.html']
  }),
  'ductbankroute.html': contract({
    workflowStep: 'fillRouting',
    standaloneInputs: ['Ductbank segment geometry, conduit assignments, cable selections, and thermal report options.'],
    projectInputs: [cables, conduits, ductbanks, ductbankPanZoom, ductbankSession, ductbankRouteData, designBasis],
    outputs: [
      output('settings.ductbankPanZoom', 'setting', 'Ductbank canvas pan and zoom state.', ['ductbankroute.html']),
      output('settings.ductbankSession', 'setting', 'Ductbank page session state.', ['ductbankroute.html']),
      output('settings.ductbankRouteData', 'setting', 'Selected ductbank route handoff data.', ['ductbankroute.html']),
      exportOnly('Ductbank calculation reports and route exports.', ['projectreport.html'])
    ],
    readiness: ready('Ready when ductbanks or conduits exist and selected cables can be assigned to underground routes.', ['No underground raceways, missing conduit group geometry, or no assignable cables.']),
    downstream: ['optimalRoute.html', 'projectreport.html']
  }),
  'cabletrayfill.html': contract({
    workflowStep: 'fillRouting',
    standaloneInputs: ['Direct tray dimensions, selected cable rows, imported fill data, and fill calculation settings.'],
    projectInputs: [cables, trays, designBasis],
    outputs: [
      output('settings.trayFillData', 'setting', 'Selected tray and cable context handed off from Raceway Schedule.', ['cabletrayfill.html']),
      exportOnly('Tray fill calculation tables and reports.', ['designrulechecker.html', 'projectreport.html'])
    ],
    readiness: ready('Ready when at least one tray and at least one schedule-ready cable are available.', ['No trays, no schedule-ready cables, or cable dimensions are missing.']),
    downstream: ['designrulechecker.html', 'optimalRoute.html', 'projectreport.html']
  }),
  'conduitfill.html': contract({
    workflowStep: 'fillRouting',
    standaloneInputs: ['Direct conduit type, trade size, cable set, and fill calculation settings.'],
    projectInputs: [cables, conduits, designBasis],
    outputs: [
      output('settings.conduitFillData', 'setting', 'Selected conduit and cable context handed off from Raceway Schedule.', ['conduitfill.html']),
      exportOnly('Conduit fill calculation tables and reports.', ['designrulechecker.html', 'projectreport.html'])
    ],
    readiness: ready('Ready when a conduit context and cable dimensions are available.', ['No conduits, no selected cable set, or missing cable diameter data.']),
    downstream: ['conduitbend.html', 'designrulechecker.html', 'projectreport.html']
  }),
  'conduitbend.html': contract({
    workflowStep: 'fillRouting',
    standaloneInputs: ['Conduit run bend list, pull-box locations, layout inputs, and imported route bends.'],
    projectInputs: [conduits, cables, designBasis, approvals],
    outputs: [
      output('studyResults.conduitBendSchedule', 'study-result', 'Conduit bend schedule results, pull-box recommendations, and visual layout inputs.', ['projectreport.html']),
      studyApprovalOutput,
      exportOnly('Bend schedule reports and pull-box layout exports.', ['projectreport.html'])
    ],
    readiness: ready('Ready when conduit runs include bend geometry or imported bend rows.', ['No conduit run inputs or invalid bend angles.']),
    downstream: ['projectreport.html']
  }),
  'supportspan.html': contract({
    workflowStep: 'fillRouting',
    standaloneInputs: ['Tray dimensions, load class, support span, cable weight, and material assumptions.'],
    projectInputs: [trays, cables, designBasis],
    outputs: [
      exportOnly('Support span checks and support recommendations.', ['projectreport.html'])
    ],
    readiness: ready('Ready when span, tray class, and applied load values are valid.', ['Missing tray span, unsupported load class, or invalid cable weight.']),
    downstream: ['trayhardwarebom.html', 'projectreport.html']
  }),
  'seismicBracing.html': contract({
    workflowStep: 'studies',
    standaloneInputs: ['Seismic force inputs, brace spacing, tray/equipment weights, and anchorage assumptions.'],
    projectInputs: [trays, equipment, cables, designBasis],
    outputs: [
      exportOnly('Seismic bracing calculation summaries and reports.', ['structuralcombinations.html', 'projectreport.html'])
    ],
    readiness: ready('Ready when seismic design values and supported weights are valid.', ['Missing seismic coefficients, support spacing, or tributary weight data.']),
    downstream: ['structuralcombinations.html', 'projectreport.html']
  }),
  'cableFaultBracing.html': contract({
    workflowStep: 'studies',
    standaloneInputs: ['Fault current, cable spacing, cleat spacing, system type, and safety factor inputs.'],
    projectInputs: [cables, projectInput('studyResults.shortCircuit', 'study-result', false, 'Fault current results used to seed bracing current inputs.'), designBasis],
    outputs: [
      exportOnly('Fault cable bracing requirements and cleat force reports.', ['projectreport.html'])
    ],
    readiness: ready('Ready when fault current, spacing, and cleat data are valid.', ['Missing fault current, invalid spacing, or unsupported system type.']),
    downstream: ['projectreport.html']
  }),
  'trayhardwarebom.html': contract({
    workflowStep: 'fillRouting',
    standaloneInputs: ['Tray segment geometry, product catalog selections, cover options, and QR settings.'],
    projectInputs: [trays, cables, designBasis],
    outputs: [
      output('settings.trayHardwareCatalogCustomProducts', 'setting', 'Custom tray hardware catalog rows.', ['trayhardwarebom.html']),
      exportOnly('Tray hardware bill of materials, QR labels, and cut/fitting reports.', ['procurementschedule.html', 'projectreport.html'])
    ],
    readiness: ready('Ready when tray geometry is present and catalog assumptions are selected.', ['No tray geometry or incomplete catalog/product assumptions.']),
    downstream: ['procurementschedule.html', 'projectreport.html']
  }),
  'clashdetect.html': contract({
    workflowStep: 'fillRouting',
    standaloneInputs: ['Manual equipment/raceway geometry, clearance rules, and imported layout data.'],
    projectInputs: [equipment, trays, conduits, ductbanks, designBasis],
    outputs: [
      exportOnly('Clash reports and clearance findings.', ['designrulechecker.html', 'projectreport.html'])
    ],
    readiness: ready('Ready when at least two geometry-bearing model elements can be checked.', ['Missing coordinates, dimensions, or clearance rules.']),
    downstream: ['designrulechecker.html', 'projectreport.html']
  }),
  'designrulechecker.html': contract({
    workflowStep: 'studies',
    standaloneInputs: ['Rule toggles, accepted-risk notes, and manual validation runs.'],
    projectInputs: [equipment, oneLine, cables, trays, conduits, ductbanks, studies, latestRouteResults, designBasis],
    outputs: [
      output('settings.drcAcceptedFindings', 'setting', 'Accepted design rule findings with engineer notes.', ['designrulechecker.html', 'projectreport.html']),
      exportOnly('Design rule checker findings and CSV reports.', ['designcoach.html', 'projectreport.html'])
    ],
    readiness: ready('Ready when the project contains model data for at least one enabled rule.', ['No checkable model data or all applicable rules are skipped.']),
    downstream: ['designcoach.html', 'projectreport.html']
  }),
  'designcoach.html': contract({
    workflowStep: 'studies',
    standaloneInputs: ['Manual coaching run selections and recommendation review notes.'],
    projectInputs: [equipment, oneLine, cables, trays, conduits, ductbanks, studies, designBasis],
    outputs: [
      output('settings.coachAuditTrail', 'setting', 'Design coach recommendation audit records.', ['projectreport.html']),
      exportOnly('Design coach recommendation reports.', ['projectreport.html'])
    ],
    readiness: ready('Ready when saved studies or schedule data can produce actionable recommendations.', ['No study results or insufficient project data for recommendations.']),
    downstream: ['projectreport.html']
  }),
  'spoolsheets.html': contract({
    workflowStep: 'deliverables',
    standaloneInputs: ['Manual route geometry, spool grouping choices, and imported route data.'],
    projectInputs: [trays, cables, conduits, ductbanks, studies, latestRouteResults, reportSnapshots, lifecyclePackages, designBasis],
    outputs: [
      exportOnly('Spool sheets and geometry handoff packages.', ['projectreport.html'])
    ],
    readiness: ready('Ready when route geometry or saved route results are available for spool grouping.', ['No route geometry, no tray path coordinates, or no route results.']),
    downstream: ['projectreport.html']
  }),
  'windload.html': contract({
    workflowStep: 'studies',
    standaloneInputs: ['Wind speed, exposure, height, tray dimensions, cover condition, and fill profile.'],
    projectInputs: [trays, cables, designBasis],
    outputs: [
      exportOnly('Tray wind load calculations and schedule-mode reports.', ['structuralcombinations.html', 'projectreport.html'])
    ],
    readiness: ready('Ready when wind inputs and tray dimensions are valid.', ['Missing wind speed, exposure, tray width, or span.']),
    downstream: ['structuralcombinations.html', 'projectreport.html']
  }),
  'structuralcombinations.html': contract({
    workflowStep: 'studies',
    standaloneInputs: ['Dead/live/wind/seismic load cases, factors, and combination selections.'],
    projectInputs: [equipment, trays, projectInput('studyResults.windLoad', 'study-result', false, 'Wind study results when available.'), designBasis],
    outputs: [
      exportOnly('Combined structural load tables and governing case reports.', ['projectreport.html'])
    ],
    readiness: ready('Ready when at least one load case and one combination are defined.', ['Missing load cases, invalid factors, or no selected combinations.']),
    downstream: ['projectreport.html']
  }),
  'seismicwindcombined.html': contract({
    workflowStep: 'studies',
    standaloneInputs: ['Seismic and wind forces, load directions, and combined check assumptions.'],
    projectInputs: [trays, equipment, cables, designBasis],
    outputs: [
      exportOnly('Seismic plus wind combined load checks.', ['projectreport.html'])
    ],
    readiness: ready('Ready when both seismic and wind inputs are valid for the selected element.', ['Missing seismic force, wind force, or tributary element data.']),
    downstream: ['projectreport.html']
  }),
  'loadcombinations.html': contract({
    workflowStep: 'studies',
    standaloneInputs: ['Load case magnitudes, code factors, and combination table selections.'],
    projectInputs: [equipment, trays, designBasis],
    outputs: [
      exportOnly('Load combination summaries and controlling load reports.', ['projectreport.html'])
    ],
    readiness: ready('Ready when load cases and factors are defined.', ['Missing load case values or invalid factor sets.']),
    downstream: ['projectreport.html']
  }),
  'optimalRoute.html': contract({
    workflowStep: 'fillRouting',
    standaloneInputs: ['Manual cable/raceway imports, route constraints, geometry settings, and optimization options.'],
    projectInputs: [...racewayInputs, routeSession],
    outputs: [
      output('settings.latestRouteResults', 'setting', 'Latest route result batch with path choices, lengths, warnings, and failed routes.', ['pullcards.html', 'spoolsheets.html', 'projectreport.html']),
      output('cableSchedule', 'schedule', 'Cable assignment updates written after route edits.', ['cableschedule.html']),
      output('settings.ctrSession', 'setting', 'Optimal Route working session values.', ['optimalRoute.html']),
      output('settings.trayFillData', 'setting', 'Tray fill handoff data opened from route results.', ['cabletrayfill.html']),
      output('settings.conduitFillData', 'setting', 'Conduit fill handoff data opened from route results.', ['conduitfill.html']),
      output('settings.ductbankRouteData', 'setting', 'Ductbank route handoff data opened from route results.', ['ductbankroute.html']),
      exportOnly('Route result CSV, summaries, and segment exports.', ['pullcards.html', 'projectreport.html'])
    ],
    readiness: ready('Ready when routing-ready cables and routeable raceways with geometry are available.', ['No routing-ready cables, no raceways, invalid raceway references, or missing geometry.']),
    downstream: ['pullcards.html', 'spoolsheets.html', 'projectreport.html']
  }),
  'pullcards.html': contract({
    workflowStep: 'deliverables',
    standaloneInputs: ['Imported route workbook, manual route rows, QR options, and pull grouping controls.'],
    projectInputs: [cables, trays, conduits, ductbanks, studies, latestRouteResults, reportSnapshots, lifecyclePackages, designBasis],
    outputs: [
      exportOnly('Pull cards, QR payloads, pull tables, and route visual exports.', ['projectreport.html'])
    ],
    readiness: ready('Ready when route results or imported route rows can be grouped into pulls.', ['No successful route results or no import rows with route signatures.']),
    downstream: ['projectreport.html']
  }),
  'procurementschedule.html': contract({
    workflowStep: 'deliverables',
    standaloneInputs: ['Cable cut imports, reel sizes, tolerance settings, and procurement options.'],
    projectInputs: [cables, latestRouteResults, designBasis],
    outputs: [
      exportOnly('Procurement schedule, reel assignment, and material summary exports.', ['costestimate.html', 'projectreport.html'])
    ],
    readiness: ready('Ready when routed or imported cable lengths can be aggregated by cable specification.', ['No cable cuts, missing cable type/size, or invalid reel settings.']),
    downstream: ['costestimate.html', 'projectreport.html']
  }),
  'costestimate.html': contract({
    workflowStep: 'deliverables',
    standaloneInputs: ['Manual quantities, labor rates, custom price book imports, and estimate assumptions.'],
    projectInputs: [cables, trays, conduits, ductbanks, studies, routeResultsStudy, latestRouteResults, projectInput('settings.customPricing', 'setting', false, 'Saved custom pricing book used to override default estimator unit prices.'), designBasis],
    outputs: [
      output('settings.customPricing', 'setting', 'Custom pricing book and estimator overrides.', ['costestimate.html']),
      exportOnly('Cost estimate tables and bid-support exports.', ['projectreport.html'])
    ],
    readiness: ready('Ready when quantities and pricing assumptions are available.', ['No quantities, missing unit pricing, or invalid labor assumptions.']),
    downstream: ['projectreport.html']
  }),
  'submittal.html': contract({
    workflowStep: 'deliverables',
    standaloneInputs: ['Package metadata, selected sections, attached exports, and reviewer fields.'],
    projectInputs: deliverableInputs,
    outputs: [
      exportOnly('Submittal package documents and spreadsheets.', ['projectreport.html'])
    ],
    readiness: ready('Ready when required package sections have source data and review gates are closed.', ['Missing source sections, open design gates, or no package metadata.']),
    downstream: ['projectreport.html']
  }),
  'projectreport.html': contract({
    workflowStep: 'deliverables',
    standaloneInputs: ['Report package selections, cover sheet data, revision rows, and manual assumptions.'],
    projectInputs: [...deliverableInputs, lifecyclePackages, tccSettings],
    outputs: [
      output('settings.reportSnapshots', 'setting', 'Saved report package snapshots.', ['workflowdashboard.html', 'projectreport.html']),
      exportOnly('Project report previews, PDF/print output, and report spreadsheets.')
    ],
    readiness: ready('Ready when selected report sections have source data and required review gates are complete.', ['No reportable sections, open review gates, or missing cover/revision metadata.']),
    downstream: ['submittal.html']
  }),
  'productconfig.html': contract({
    workflowStep: 'deliverables',
    standaloneInputs: ['Tray loading, environment, material, width/depth, and application selections.'],
    projectInputs: [cables, trays, designBasis],
    outputs: [
      exportOnly('Product configuration recommendations and specification text.', ['procurementschedule.html', 'projectreport.html'])
    ],
    readiness: ready('Ready when tray application, environment, span, and cable load inputs are valid.', ['Missing application, invalid span, or insufficient tray sizing inputs.']),
    downstream: ['procurementschedule.html', 'projectreport.html']
  }),
  'demandschedule.html': contract({
    workflowStep: 'studies',
    standaloneInputs: ['Manual demand rows, diversity factors, load classes, and imported load schedules.'],
    projectInputs: [loads, equipment, panels, designBasis],
    outputs: [
      exportOnly('Demand schedule summaries and load aggregation exports.', ['loadFlow.html', 'generatorsizing.html', 'projectreport.html'])
    ],
    readiness: ready('Ready when load rows have demand values and aggregation factors.', ['No load rows, missing demand values, or invalid demand factors.']),
    downstream: ['loadFlow.html', 'generatorsizing.html', 'projectreport.html']
  }),
  'intlCableSize.html': contract({
    workflowStep: 'studies',
    standaloneInputs: ['International cable sizing inputs, installation conditions, conductor material, and standards selections.'],
    projectInputs: [cables, loads, designBasis],
    outputs: [
      exportOnly('International cable sizing recommendations and reports.', ['cableschedule.html', 'projectreport.html'])
    ],
    readiness: ready('Ready when load current, installation method, conductor material, and voltage are valid.', ['Missing load current, unsupported installation method, or invalid conductor settings.']),
    downstream: ['cableschedule.html', 'projectreport.html']
  }),
  'iec60287.html': contract({
    workflowStep: 'studies',
    standaloneInputs: ['IEC 60287 thermal inputs, soil/ambient conditions, conductor data, and installation method.'],
    projectInputs: [cables, designBasis, approvals],
    outputs: [
      output('studyResults.iec60287', 'study-result', 'Saved IEC 60287 ampacity result and input snapshot.', ['projectreport.html']),
      studyApprovalOutput,
      exportOnly('IEC 60287 calculation report exports.', ['projectreport.html'])
    ],
    readiness: ready('Ready when cable thermal inputs and installation conditions are valid.', ['Missing conductor data, thermal resistivity, ambient values, or installation geometry.']),
    downstream: ['projectreport.html']
  }),
  'cablethermalenv.html': contract({
    workflowStep: 'studies',
    standaloneInputs: ['Cable construction, ambient conditions, grouping, installation type, and optional load profile inputs.'],
    projectInputs: [designBasis, approvals],
    outputs: [
      output('studyResults.cableThermalEnvironment', 'study-result', 'Saved unified cable thermal environment comparison and load-profile result.', ['designcoach.html', 'projectreport.html']),
      studyApprovalOutput,
      exportOnly('Cable thermal environment comparison tables and CSV exports.', ['projectreport.html'])
    ],
    readiness: ready('Ready when cable, ambient, grouping, and at least one installation condition are valid.', ['Missing cable size, invalid ambient values, no selected installation, or malformed load profile data.']),
    downstream: ['designcoach.html', 'projectreport.html']
  }),
  'tcc.html': contract({
    workflowStep: 'studies',
    standaloneInputs: ['Protective device library selections, relay settings, annotations, chart ranges, and selected references.'],
    projectInputs: [oneLine, equipment, cables, projectInput('studyResults.shortCircuit', 'study-result', false, 'Fault current values used for coordination context.'), projectInput('studyResults.arcFlash', 'study-result', false, 'Arc flash results used for equipment overlays.'), tccSettings],
    outputs: [
      output('settings.tccSettings', 'setting', 'Protective device selections, settings, annotations, chart options, and assignments.', ['shortCircuit.html', 'arcFlash.html', 'projectreport.html']),
      output('oneLineDiagram', 'model', 'One-line protection zone and context updates from TCC review flows.', ['oneline.html']),
      output('studyResults.shortCircuit', 'study-result', 'Short-circuit result generated from TCC short-circuit helper flows.', ['arcFlash.html', 'equipmentevaluation.html']),
      output('studyResults.tcc', 'study-result', 'Coordination analysis snapshots when saved from TCC review flows.', ['projectreport.html'])
    ],
    readiness: ready('Ready when at least two protective devices or a selected one-line context can be plotted.', ['No devices selected, missing settings, or no usable fault current context.']),
    downstream: ['shortCircuit.html', 'arcFlash.html', 'equipmentevaluation.html', 'projectreport.html']
  }),
  'harmonics.html': contract({
    workflowStep: 'studies',
    standaloneInputs: ['Harmonic source data, impedance assumptions, bus selections, and chart settings.'],
    projectInputs: [oneLine, equipment, projectInput('studyResults.loadFlow', 'study-result', false, 'Operating bus values used for harmonic context.'), designBasis],
    outputs: [
      output('studyResults.harmonics', 'study-result', 'Saved harmonic distortion results and source contributions.', ['designcoach.html', 'projectreport.html']),
      exportOnly('Harmonic chart and report exports.', ['projectreport.html'])
    ],
    readiness: ready('Ready when harmonic sources and bus context exist or direct source inputs are valid.', ['No harmonic sources or missing bus/impedance data.']),
    downstream: ['designcoach.html', 'projectreport.html']
  }),
  'capacitorbank.html': contract({
    workflowStep: 'studies',
    standaloneInputs: ['Power factor target, load kW/kVAR, short-circuit strength, and capacitor step settings.'],
    projectInputs: [loads, projectInput('studyResults.loadFlow', 'study-result', false, 'Bus P/Q values used to seed existing power factor.'), projectInput('studyResults.shortCircuit', 'study-result', false, 'Short-circuit strength used for resonance checks.'), designBasis, approvals],
    outputs: [
      output('studyResults.capacitorBank', 'study-result', 'Saved capacitor bank sizing, step recommendation, and resonance warning result.', ['frequencyscan.html', 'projectreport.html']),
      studyApprovalOutput,
      exportOnly('Capacitor bank sizing report exports.', ['projectreport.html'])
    ],
    readiness: ready('Ready when real/reactive load and target power factor are valid.', ['Missing load data, invalid target power factor, or unavailable short-circuit context for resonance screening.']),
    downstream: ['frequencyscan.html', 'projectreport.html']
  }),
  'frequencyscan.html': contract({
    workflowStep: 'studies',
    standaloneInputs: ['System impedance, capacitor size, harmonic orders, and scan range settings.'],
    projectInputs: [projectInput('studyResults.capacitorBank', 'study-result', false, 'Capacitor bank sizing used as scan context.'), projectInput('studyResults.shortCircuit', 'study-result', false, 'System fault strength used for impedance estimates.'), designBasis, approvals],
    outputs: [
      output('studyResults.frequencyScan', 'study-result', 'Saved frequency scan points and resonance warnings.', ['harmonics.html', 'projectreport.html']),
      studyApprovalOutput,
      exportOnly('Frequency scan plot and report exports.', ['projectreport.html'])
    ],
    readiness: ready('Ready when impedance and scan range inputs are valid.', ['Missing impedance, capacitor size, or scan range inputs.']),
    downstream: ['harmonics.html', 'projectreport.html']
  }),
  'voltageflicker.html': contract({
    workflowStep: 'studies',
    standaloneInputs: ['Load step, source impedance, repetition rate, and flicker criteria inputs.'],
    projectInputs: [loads, projectInput('studyResults.shortCircuit', 'study-result', false, 'Source strength used to estimate voltage change.'), designBasis, approvals],
    outputs: [
      output('studyResults.voltageFlicker', 'study-result', 'Saved flicker screening result and compliance status.', ['projectreport.html']),
      studyApprovalOutput,
      exportOnly('Voltage flicker report exports.', ['projectreport.html'])
    ],
    readiness: ready('Ready when load step and source strength inputs are valid.', ['Missing load step, repetition rate, or source impedance/fault strength.']),
    downstream: ['projectreport.html']
  }),
  'busdust.html': contract({
    workflowStep: 'studies',
    standaloneInputs: ['Bus duct load, length, material, orientation, ambient, and fault stress inputs.'],
    projectInputs: [equipment, loads, projectInput('studyResults.shortCircuit', 'study-result', false, 'Fault current used for bus stress screening.'), designBasis, approvals],
    outputs: [
      output('studyResults.busDuctSizing', 'study-result', 'Saved bus duct sizing, voltage drop, derating, and fault stress result.', ['projectreport.html']),
      studyApprovalOutput,
      exportOnly('Bus duct sizing report exports.', ['projectreport.html'])
    ],
    readiness: ready('Ready when load current, length, voltage, and fault inputs are valid.', ['Missing current, length, busway rating context, or fault current.']),
    downstream: ['projectreport.html']
  }),
  'sustainability.html': contract({
    workflowStep: 'studies',
    standaloneInputs: ['Material quantities, conductor types, route lengths, and carbon factor assumptions.'],
    projectInputs: [cables, trays, conduits, iec60287Study, designBasis, approvals],
    outputs: [
      output('studyResults.sustainabilityFootprint', 'study-result', 'Saved material and carbon footprint summary.', ['projectreport.html']),
      studyApprovalOutput,
      exportOnly('Sustainability footprint exports.', ['projectreport.html'])
    ],
    readiness: ready('Ready when material quantities or schedule-derived quantities are available.', ['No quantities, missing material classification, or invalid carbon factors.']),
    downstream: ['projectreport.html']
  }),
  'battery.html': contract({
    workflowStep: 'studies',
    standaloneInputs: ['Duty cycle, chemistry, runtime, UPS power, temperature, margin, and rack layout inputs.'],
    projectInputs: [loads, equipment, designBasis, approvals],
    outputs: [
      output('studyResults.batterySizing', 'study-result', 'Saved battery/UPS sizing, runtime, and rack layout result.', ['bessHazard.html', 'projectreport.html']),
      studyApprovalOutput,
      exportOnly('Battery sizing and rack layout exports.', ['projectreport.html'])
    ],
    readiness: ready('Ready when duty cycle, chemistry, load, and runtime values are valid.', ['Missing load profile, invalid chemistry, or invalid runtime/margin values.']),
    downstream: ['bessHazard.html', 'projectreport.html']
  }),
  'generatorsizing.html': contract({
    workflowStep: 'studies',
    standaloneInputs: ['Load profile, starting method, power factor, voltage, and generator margin inputs.'],
    projectInputs: [loads, equipment, projectInput('studyResults.motorStart', 'study-result', false, 'Motor starting results used for starting kVA context.'), designBasis, approvals],
    outputs: [
      output('studyResults.generatorSizing', 'study-result', 'Saved generator sizing and starting capacity result.', ['projectreport.html']),
      studyApprovalOutput,
      exportOnly('Generator sizing report exports.', ['projectreport.html'])
    ],
    readiness: ready('Ready when load and starting assumptions are valid.', ['No load profile, invalid starting assumptions, or missing voltage/power factor values.']),
    downstream: ['projectreport.html']
  }),
  'ibr.html': contract({
    workflowStep: 'studies',
    standaloneInputs: ['PV/BESS inverter ratings, control mode, fault contribution, ride-through, and compliance inputs.'],
    projectInputs: [equipment, oneLine, projectInput('studyResults.loadFlow', 'study-result', false, 'Operating-point context for inverter models.'), pvResult, bessResult, faultResult, voltVarResult, designBasis, approvals],
    outputs: [
      output('studyResults.ibr', 'study-result', 'Saved inverter-based resource model, fault contribution, and ride-through results.', ['derinterconnect.html', 'shortCircuit.html', 'projectreport.html']),
      studyApprovalOutput,
      exportOnly('IBR model and compliance exports.', ['projectreport.html'])
    ],
    readiness: ready('Ready when inverter ratings and control assumptions are valid.', ['Missing inverter rating, control mode, or interconnection voltage data.']),
    downstream: ['derinterconnect.html', 'shortCircuit.html', 'projectreport.html']
  }),
  'derinterconnect.html': contract({
    workflowStep: 'studies',
    standaloneInputs: ['DER size, utility limits, protection settings, voltage/frequency ride-through, and checklist inputs.'],
    projectInputs: [equipment, oneLine, projectInput('studyResults.ibr', 'study-result', false, 'IBR model results used for DER checks.'), designBasis, approvals],
    outputs: [
      output('studyResults.derInterconnect', 'study-result', 'Saved DER interconnection screening, checklist, and pass/fail result.', ['projectreport.html']),
      studyApprovalOutput,
      exportOnly('DER interconnection reports.', ['projectreport.html'])
    ],
    readiness: ready('Ready when DER rating, point of interconnection, and utility criteria are valid.', ['Missing DER rating, POI voltage, or utility screening thresholds.']),
    downstream: ['projectreport.html']
  }),
  'motorStart.html': contract({
    workflowStep: 'studies',
    standaloneInputs: ['Motor horsepower, voltage, starter type, inertia/load torque, and Thevenin source inputs.'],
    projectInputs: [oneLine, equipment, loads, projectInput('studyResults.loadFlow', 'study-result', false, 'Prefault voltage context.'), designBasis],
    outputs: [
      output('studyResults.motorStart', 'study-result', 'Saved motor starting current, torque, and voltage sag result.', ['generatorsizing.html', 'projectreport.html']),
      exportOnly('Motor starting charts and reports.', ['projectreport.html'])
    ],
    readiness: ready('Ready when a motor and source impedance context are valid.', ['No motor data, missing source impedance, or invalid starter parameters.']),
    downstream: ['generatorsizing.html', 'projectreport.html']
  }),
  'loadFlow.html': contract({
    workflowStep: 'studies',
    standaloneInputs: ['Manual buses, branches, loads, sources, and solver settings.'],
    projectInputs: [oneLine, equipment, loads, cables, designBasis],
    outputs: [
      output('studyResults.loadFlow', 'study-result', 'Saved bus voltage, branch loading, and power flow result.', ['quasidynamic.html', 'voltagestability.html', 'capacitorbank.html', 'projectreport.html']),
      exportOnly('Load flow reports and charts.', ['projectreport.html'])
    ],
    readiness: ready('Ready when the model has a source, connected buses, and load data.', ['No source, disconnected network, or invalid load/bus data.']),
    downstream: ['quasidynamic.html', 'voltagestability.html', 'projectreport.html']
  }),
  'quasidynamic.html': contract({
    workflowStep: 'studies',
    standaloneInputs: ['Time-series load, generation profile, timestep settings, and voltage criteria.'],
    projectInputs: [oneLine, loads, projectInput('studyResults.loadFlow', 'study-result', false, 'Base load flow model and operating point.'), designBasis, approvals],
    outputs: [
      output('studyResults.quasiDynamic', 'study-result', 'Saved quasi-dynamic load flow time-series result.', ['projectreport.html']),
      studyApprovalOutput,
      exportOnly('Quasi-dynamic profile plots and exports.', ['projectreport.html'])
    ],
    readiness: ready('Ready when a base model and time-series profile are valid.', ['Missing base load-flow context or invalid time-series data.']),
    downstream: ['projectreport.html']
  }),
  'voltagestability.html': contract({
    workflowStep: 'studies',
    standaloneInputs: ['PV/QV curve inputs, selected bus, load scaling, and solver settings.'],
    projectInputs: [oneLine, loads, projectInput('studyResults.loadFlow', 'study-result', false, 'Base case load-flow solution.'), designBasis, approvals],
    outputs: [
      output('studyResults.voltageStability', 'study-result', 'Saved PV/QV curve results and stability margins.', ['projectreport.html']),
      studyApprovalOutput,
      exportOnly('Voltage stability curve exports.', ['projectreport.html'])
    ],
    readiness: ready('Ready when a converged base case and target bus are available.', ['No converged base case, missing target bus, or invalid load scaling.']),
    downstream: ['projectreport.html']
  }),
  'shortCircuit.html': contract({
    workflowStep: 'studies',
    standaloneInputs: ['Manual source impedance, fault location, equipment ratings, and device settings.'],
    projectInputs: [oneLine, equipment, cables, tccSettings, designBasis],
    outputs: [
      output('studyResults.shortCircuit', 'study-result', 'Saved short-circuit duty result by bus or device.', ['arcFlash.html', 'tcc.html', 'equipmentevaluation.html', 'projectreport.html']),
      exportOnly('Short-circuit reports and duty tables.', ['projectreport.html'])
    ],
    readiness: ready('Ready when the one-line has a source and faultable buses/devices.', ['No source, missing impedance/fault data, or disconnected fault location.']),
    downstream: ['tcc.html', 'arcFlash.html', 'equipmentevaluation.html', 'projectreport.html']
  }),
  'iec60909.html': contract({
    workflowStep: 'studies',
    standaloneInputs: ['IEC network source data, transformer/cable impedance, voltage factor, and fault location inputs.'],
    projectInputs: [oneLine, equipment, cables, tccSettings, designBasis, approvals],
    outputs: [
      output('studyResults.iec60909', 'study-result', 'Saved IEC 60909 short-circuit current result.', ['projectreport.html']),
      studyApprovalOutput,
      exportOnly('IEC 60909 calculation reports.', ['projectreport.html'])
    ],
    readiness: ready('Ready when source, voltage factor, and impedance data are valid.', ['Missing source data, unsupported voltage base, or invalid impedance inputs.']),
    downstream: ['projectreport.html']
  }),
  'arcFlash.html': contract({
    workflowStep: 'studies',
    standaloneInputs: ['Manual equipment data, working distance, clearing time, enclosure, and label options.'],
    projectInputs: [oneLine, equipment, cables, projectInput('studyResults.shortCircuit', 'study-result', true, 'Fault current results required for arc flash calculations.'), tccSettings, designBasis],
    outputs: [
      output('studyResults.arcFlash', 'study-result', 'Saved incident energy, boundary, PPE, and label data.', ['tcc.html', 'designcoach.html', 'projectreport.html']),
      exportOnly('Arc flash CSV/PDF reports and SVG label files.', ['projectreport.html'])
    ],
    readiness: ready('Ready when fault current and clearing time are available for target equipment.', ['Missing short-circuit result, clearing time, working distance, or equipment voltage.']),
    downstream: ['tcc.html', 'designcoach.html', 'projectreport.html']
  }),
  'dcshortcircuit.html': contract({
    workflowStep: 'studies',
    standaloneInputs: ['DC source, battery/string data, cable impedance, protection, and arc-flash inputs.'],
    projectInputs: [equipment, cables, projectInput('studyResults.batterySizing', 'study-result', false, 'Battery model context for DC fault contribution.'), designBasis, approvals],
    outputs: [
      output('studyResults.dcShortCircuit', 'study-result', 'Saved DC short-circuit and DC arc-flash screening result.', ['projectreport.html']),
      studyApprovalOutput,
      exportOnly('DC short-circuit and arc-flash reports.', ['projectreport.html'])
    ],
    readiness: ready('Ready when DC source and circuit impedance inputs are valid.', ['Missing DC source, invalid battery/cable data, or missing protection settings.']),
    downstream: ['projectreport.html']
  }),
  'differentialprotection.html': contract({
    workflowStep: 'studies',
    standaloneInputs: ['CT ratios, relay slopes, restraint settings, differential pickup, and through-fault data.'],
    projectInputs: [oneLine, equipment, projectInput('studyResults.shortCircuit', 'study-result', false, 'Through-fault current context.'), designBasis, approvals],
    outputs: [
      output('studyResults.differentialProtection', 'study-result', 'Saved differential protection settings and operating checks.', ['projectreport.html']),
      studyApprovalOutput,
      exportOnly('Differential protection reports.', ['projectreport.html'])
    ],
    readiness: ready('Ready when CTs, protected equipment, and relay settings are valid.', ['Missing CT ratios, relay pickup/slope, or protected equipment link.']),
    downstream: ['projectreport.html']
  }),
  'equipmentevaluation.html': contract({
    workflowStep: 'studies',
    standaloneInputs: ['Manual equipment rating checks, protective device context, and acceptance selections.'],
    projectInputs: [equipment, oneLine, cables, projectInput('studyResults.shortCircuit', 'study-result', true, 'Fault duty results used for equipment rating checks.'), projectInput('studyResults.arcFlash', 'study-result', false, 'Arc flash context for equipment safety review.'), tccSettings],
    outputs: [
      exportOnly('Equipment duty, interrupting rating, and evaluation reports.', ['designcoach.html', 'projectreport.html'])
    ],
    readiness: ready('Ready when equipment ratings and fault duty values are available.', ['Missing equipment SCCR/interrupt ratings or no short-circuit result.']),
    downstream: ['designcoach.html', 'projectreport.html']
  }),
  'bessHazard.html': contract({
    workflowStep: 'studies',
    standaloneInputs: ['Chemistry, rated energy, room volume, separation distances, venting, and propagation assumptions.'],
    projectInputs: [equipment, projectInput('studyResults.batterySizing', 'study-result', false, 'Battery sizing result used to seed energy and chemistry.'), designBasis, approvals],
    outputs: [
      output('studyResults.bessHazard', 'study-result', 'Saved BESS hazard, separation, propagation, and deflagration venting result.', ['projectreport.html']),
      studyApprovalOutput,
      exportOnly('BESS hazard reports.', ['projectreport.html'])
    ],
    readiness: ready('Ready when chemistry, energy, room, and exposure inputs are valid.', ['Missing rated energy, unknown chemistry, invalid room volume, or incomplete exposure distances.']),
    downstream: ['projectreport.html']
  }),
  'hazareaclassification.html': contract({
    workflowStep: 'studies',
    standaloneInputs: ['Material release data, ventilation, occupancy, ignition source, and area classification inputs.'],
    projectInputs: [equipment, designBasis, approvals],
    outputs: [
      output('studyResults.hazAreaClassification', 'study-result', 'Saved hazardous area classification result and compliance snapshot.', ['projectreport.html']),
      studyApprovalOutput,
      exportOnly('Hazardous area classification reports and drawings.', ['projectreport.html'])
    ],
    readiness: ready('Ready when release source, material, and ventilation inputs are valid.', ['Missing release source, material properties, or ventilation assumptions.']),
    downstream: ['projectreport.html']
  }),
  'insulationcoordination.html': contract({
    workflowStep: 'studies',
    standaloneInputs: ['BIL/SIL levels, arrester ratings, altitude, voltage class, and surge assumptions.'],
    projectInputs: [equipment, oneLine, projectInput('studyResults.shortCircuit', 'study-result', false, 'System strength and voltage context.'), designBasis, approvals],
    outputs: [
      output('studyResults.insulationCoordination', 'study-result', 'Saved insulation coordination and protective margin result.', ['projectreport.html']),
      studyApprovalOutput,
      exportOnly('Insulation coordination reports.', ['projectreport.html'])
    ],
    readiness: ready('Ready when voltage class, insulation level, and arrester data are valid.', ['Missing voltage class, BIL/SIL level, or arrester rating.']),
    downstream: ['projectreport.html']
  }),
  'lighting.html': contract({
    workflowStep: 'studies',
    standaloneInputs: ['Egress path geometry, fixture spacing, lumen output, battery runtime, and code criteria.'],
    projectInputs: [equipment, loads, designBasis, approvals],
    outputs: [
      output('studyResults.lighting', 'study-result', 'Saved egress lighting and emergency runtime result.', ['projectreport.html']),
      studyApprovalOutput,
      exportOnly('Lighting calculation reports.', ['projectreport.html'])
    ],
    readiness: ready('Ready when egress path and fixture assumptions are valid.', ['Missing path dimensions, fixture data, or runtime criteria.']),
    downstream: ['projectreport.html']
  }),
  'groundgrid.html': contract({
    workflowStep: 'studies',
    standaloneInputs: ['Grid geometry, soil resistivity, fault current, clearing time, surface layer, and risk points.'],
    projectInputs: [equipment, projectInput('studyResults.shortCircuit', 'study-result', false, 'Fault current context for ground grid checks.'), designBasis],
    outputs: [
      exportOnly('Ground grid safety reports and hazard map exports.', ['projectreport.html'])
    ],
    readiness: ready('Ready when grid geometry, soil model, and fault clearing inputs are valid.', ['Missing grid dimensions, soil data, fault current, or clearing time.']),
    downstream: ['projectreport.html']
  }),
  'cathodicprotection.html': contract({
    workflowStep: 'studies',
    standaloneInputs: ['Structure geometry, coating, soil resistivity, design life, anode data, measurements, and layout canvas edits.'],
    projectInputs: [equipment, designBasis, approvals],
    outputs: [
      output('studyResults.cathodicProtection', 'study-result', 'Saved CP sizing, commissioning plan, compliance history, layout, and report export payload.', ['projectreport.html']),
      studyApprovalOutput,
      exportOnly('Cathodic protection JSON/PDF reports.', ['projectreport.html'])
    ],
    readiness: ready('Ready when structure, soil, coating, and anode inputs are valid.', ['Missing structure area, soil data, coating factor, anode data, or required measurement metadata.']),
    downstream: ['projectreport.html']
  }),
  'dissimilarmetals.html': contract({
    workflowStep: 'studies',
    standaloneInputs: ['Metal pair, environment, area ratio, isolation method, and exposure assumptions.'],
    projectInputs: [equipment, designBasis],
    outputs: [
      output('studyResults.dissimilarMetals', 'study-result', 'Saved galvanic compatibility and mitigation result.', ['projectreport.html']),
      exportOnly('Dissimilar metals compatibility reports.', ['projectreport.html'])
    ],
    readiness: ready('Ready when metal pair and environment inputs are valid.', ['Missing material pair, electrolyte/environment, or area ratio.']),
    downstream: ['projectreport.html']
  }),
  'autosize.html': contract({
    workflowStep: 'studies',
    standaloneInputs: ['Load current, motor/transformer/feed type, installation conditions, conductor material, and equipment rating.'],
    projectInputs: [loads, cables, designBasis],
    outputs: [
      exportOnly('NEC auto-size recommendations and sizing reports.', ['cableschedule.html', 'projectreport.html'])
    ],
    readiness: ready('Ready when load and installation conditions are valid.', ['Missing load current, invalid equipment type, or unsupported conductor settings.']),
    downstream: ['cableschedule.html', 'projectreport.html']
  }),
  'heattracesizing.html': contract({
    workflowStep: 'studies',
    standaloneInputs: ['Pipe geometry, ambient/maintain temperatures, insulation, circuit data, and branch schedule inputs.'],
    projectInputs: [loads, equipment, designBasis, approvals],
    outputs: [
      output('studyResults.heatTraceSizing', 'study-result', 'Saved heat trace sizing active result.', ['projectreport.html']),
      output('studyResults.heatTraceSizingCircuits', 'study-result', 'Saved heat trace circuit case schedule.', ['projectreport.html']),
      studyApprovalOutput,
      exportOnly('Heat trace calculation reports and circuit exports.', ['projectreport.html'])
    ],
    readiness: ready('Ready when pipe, temperature, insulation, and circuit inputs are valid.', ['Missing pipe data, invalid temperatures, incomplete insulation, or open study approval requirements.']),
    downstream: ['projectreport.html']
  }),
  'reliability.html': contract({
    workflowStep: 'studies',
    standaloneInputs: ['Component MTBF/MTTR data, topology assumptions, and contingency screening options.'],
    projectInputs: [oneLine, equipment, designBasis],
    outputs: [
      output('studyResults.reliability', 'study-result', 'Saved reliability availability and outage result.', ['contingency.html', 'projectreport.html']),
      exportOnly('Reliability reports.', ['projectreport.html'])
    ],
    readiness: ready('Ready when eligible components have MTBF/MTTR data or direct reliability inputs.', ['No eligible components or missing reliability parameters.']),
    downstream: ['contingency.html', 'projectreport.html']
  }),
  'emf.html': contract({
    workflowStep: 'studies',
    standaloneInputs: ['Conductor geometry, current, phase arrangement, exposure criteria, and profile settings.'],
    projectInputs: [cables, trays, conduits, projectInput('studyResults.loadFlow', 'study-result', false, 'Operating current context for routed conductors.'), designBasis],
    outputs: [
      exportOnly('EMF profile plots, exposure checks, and reports.', ['projectreport.html'])
    ],
    readiness: ready('Ready when conductor geometry and current inputs are valid.', ['Missing conductor coordinates, invalid current, or unsupported phase arrangement.']),
    downstream: ['projectreport.html']
  }),
  'transientstability.html': contract({
    workflowStep: 'studies',
    standaloneInputs: ['Generator inertia, mechanical power, clearing time, transfer reactance, and fault profile inputs.'],
    projectInputs: [oneLine, equipment, projectInput('studyResults.loadFlow', 'study-result', false, 'Prefault operating point context.'), projectInput('studyResults.shortCircuit', 'study-result', false, 'Fault context for clearing checks.'), designBasis],
    outputs: [
      exportOnly('Transient stability plots and reports.', ['projectreport.html'])
    ],
    readiness: ready('Ready when generator, transfer, and fault clearing inputs are valid.', ['Missing machine data, invalid clearing time, or incomplete transfer reactance values.']),
    downstream: ['projectreport.html']
  }),
  'contingency.html': contract({
    workflowStep: 'studies',
    standaloneInputs: ['Manual contingency cases, outage selections, and pass/fail criteria.'],
    projectInputs: [oneLine, equipment, cables, projectInput('studyResults.loadFlow', 'study-result', false, 'Base flow result for contingency checks.'), projectInput('studyResults.reliability', 'study-result', false, 'Reliability context for outage prioritization.'), designBasis],
    outputs: [
      output('studyResults.contingency', 'study-result', 'Saved N-1 contingency screening result.', ['projectreport.html']),
      exportOnly('Contingency summary exports.', ['projectreport.html'])
    ],
    readiness: ready('Ready when a connected model and at least one contingency case are available.', ['No connected model, no outage candidates, or missing base operating point.']),
    downstream: ['projectreport.html']
  }),
  'voltagedropstudy.html': contract({
    workflowStep: 'studies',
    standaloneInputs: ['Manual cable length/load rows, circuit classification, voltage, and conductor settings.'],
    projectInputs: [cables, loads, projectInput('studyResults.loadFlow', 'study-result', false, 'Operating current or voltage context when available.'), designBasis],
    outputs: [
      exportOnly('Voltage drop reports and CSV exports.', ['projectreport.html'])
    ],
    readiness: ready('Ready when cable length and load/current data are available.', ['Missing cable length, missing load/current, or invalid conductor data.']),
    downstream: ['projectreport.html']
  })
};

export function getPageContract(href) {
  const normalized = normalizeHref(href);
  return PAGE_CONTRACTS_BY_HREF[normalized] || null;
}

export function getPageContractReadiness(href) {
  const normalized = normalizeHref(href);
  const pageContract = getPageContract(normalized);
  if (!pageContract) return null;
  const downstream = pageContract.downstream.map(item => ({
    href: item,
    label: routeLabel(item)
  }));
  return {
    href: normalized,
    label: routeLabel(normalized),
    terms: READINESS_VOCABULARY,
    readyWhen: pageContract.readiness.readyWhen,
    blockers: [...pageContract.readiness.blockers],
    downstream,
    downstreamText: downstream.length
      ? downstream.map(item => item.label).join(', ')
      : 'No downstream handoff declared.'
  };
}

export function getPageContractReadinessMessages(href) {
  const readiness = getPageContractReadiness(href);
  if (!readiness) return null;
  return {
    ready: `${READINESS_VOCABULARY.ready}: ${readiness.readyWhen}`,
    missingInputs: `${READINESS_VOCABULARY.missingInputs}: ${readiness.blockers.join('; ')}`,
    downstreamHandoff: `${READINESS_VOCABULARY.downstreamHandoff}: ${readiness.downstreamText}`
  };
}

export function getPageContractsForSection(section) {
  return NAV_ROUTES
    .filter(route => route.section === section)
    .map(route => ({ route, contract: getPageContract(route.href) }))
    .filter(item => item.contract);
}

export function getPageContractCoverage(routes = NAV_ROUTES) {
  const scopedRoutes = routes.filter(route => CONTRACT_SECTIONS.has(route.section));
  const routeHrefs = new Set(scopedRoutes.map(route => route.href));
  const contractHrefs = Object.keys(PAGE_CONTRACTS_BY_HREF);
  return {
    totalRoutes: scopedRoutes.length,
    totalContracts: contractHrefs.length,
    missing: scopedRoutes.filter(route => !PAGE_CONTRACTS_BY_HREF[route.href]).map(route => route.href),
    extra: contractHrefs.filter(href => !routeHrefs.has(href)),
    routes: scopedRoutes
  };
}
