export const DESIGN_BASIS_STORAGE_KEY = 'designBasis';

export const DEFAULT_DESIGN_BASIS = {
  schemaVersion: 1,
  codeBasis: {
    primaryCode: 'NEC',
    edition: '2023',
    jurisdiction: '',
    ahj: '',
    unitSystem: 'imperial'
  },
  sizingDefaults: {
    conductorMaterial: 'copper',
    insulationType: 'THWN-2',
    temperatureRatingC: 75,
    installationType: 'conduit',
    defaultPowerFactor: 0.9,
    voltageDropLimitPct: 3,
    continuousLoadPolicy: 'assume-continuous'
  },
  routingDefaults: {
    defaultLengthFt: 100,
    defaultTrayId: 'TR-AUTO-001',
    defaultTrayWidthIn: 12,
    defaultTrayDepthIn: 4,
    defaultTrayElevationFt: 10,
    fillLimitPct: 40,
    fieldRoutePolicy: 'allow-field-legs'
  },
  studyPrerequisites: {
    requireUtilityFault: true,
    requireProtectiveDeviceSettings: true,
    requireEquipmentCoordinates: true,
    requireArcFlashInputs: true
  },
  approvalRules: {
    generatedRecordsRequireReview: true,
    routeResultsRequireReview: true,
    studiesRequireReview: true,
    releaseRequiresReviewer: true,
    reviewer: ''
  },
  updatedAt: ''
};

const PRIMARY_CODES = new Set(['NEC', 'CEC', 'IEC']);
const UNIT_SYSTEMS = new Set(['imperial', 'metric']);
const CONDUCTOR_MATERIALS = new Set(['copper', 'aluminum']);
const TEMP_RATINGS = new Set([60, 75, 90]);
const INSTALLATION_TYPES = new Set(['conduit', 'tray', 'direct-buried']);
const CONTINUOUS_POLICIES = new Set(['assume-continuous', 'assume-noncontinuous', 'require-duty-field']);
const FIELD_ROUTE_POLICIES = new Set(['allow-field-legs', 'require-raceway-only']);

function clone(value) {
  return JSON.parse(JSON.stringify(value));
}

function hasValue(value) {
  return value !== null && value !== undefined && String(value).trim() !== '';
}

function text(value, fallback = '') {
  const next = String(value ?? '').trim();
  return next || fallback;
}

function numberValue(value, fallback, { min = null, max = null } = {}) {
  const parsed = Number.parseFloat(value);
  let next = Number.isFinite(parsed) ? parsed : fallback;
  if (min !== null && next < min) next = min;
  if (max !== null && next > max) next = max;
  return next;
}

function choice(value, allowed, fallback) {
  return allowed.has(value) ? value : fallback;
}

function boolValue(value, fallback) {
  return typeof value === 'boolean' ? value : fallback;
}

function meaningfulRecords(records) {
  return Array.isArray(records)
    ? records.filter(row => row && typeof row === 'object' && Object.values(row).some(hasValue))
    : [];
}

function routeResultRows(routeResults) {
  if (Array.isArray(routeResults)) return meaningfulRecords(routeResults);
  if (routeResults && typeof routeResults === 'object') {
    if (Array.isArray(routeResults.batchResults)) return meaningfulRecords(routeResults.batchResults);
    if (Array.isArray(routeResults.routeResults)) return meaningfulRecords(routeResults.routeResults);
    if (Array.isArray(routeResults.latestRouteData)) return meaningfulRecords(routeResults.latestRouteData);
    if (Array.isArray(routeResults.results)) return meaningfulRecords(routeResults.results);
  }
  return [];
}

function studyHasResults(result) {
  if (!result) return false;
  if (Array.isArray(result)) return result.length > 0;
  if (typeof result === 'object') return Object.keys(result).some(key => hasValue(result[key]));
  return hasValue(result);
}

function studyKeys(studies = {}) {
  if (!studies || typeof studies !== 'object') return [];
  return Object.keys(studies).filter(key => studyHasResults(studies[key]));
}

function approvalIsReviewed(approval) {
  if (!approval || typeof approval !== 'object') return false;
  const status = text(approval.status).toLowerCase();
  if (['reviewed', 'approved', 'accepted', 'resolved'].includes(status)) return true;
  if (['flagged', 'open', 'pending', 'rejected', 'needs-review'].includes(status)) return false;
  return hasValue(approval.reviewedBy) && hasValue(approval.approvedAt);
}

function countGeneratedRecords(project = {}) {
  const recordGroups = [
    project.equipment,
    project.loads,
    project.cables,
    project.trays,
    project.conduits,
    project.ductbanks,
    project.panels,
    project.mccLineups
  ];
  const scheduleCount = recordGroups.reduce((count, rows) => count + meaningfulRecords(rows).filter(row => (
    row._workflowAutoGenerated || row._workflowBasis || row._workflowRacewayAssigned
  )).length, 0);
  const oneLineSheets = Array.isArray(project.oneLine?.sheets) ? project.oneLine.sheets : [];
  const oneLineCount = oneLineSheets.reduce((count, sheet) => {
    const components = meaningfulRecords(sheet.components).filter(component => component._workflowAutoGenerated || component._workflowBasis).length;
    const connections = meaningfulRecords(sheet.connections).filter(connection => connection._workflowAutoGenerated || connection._workflowBasis).length;
    return count + components + connections;
  }, 0);
  return scheduleCount + oneLineCount;
}

function hasEquipmentCoordinates(equipment = []) {
  const rows = meaningfulRecords(equipment);
  if (!rows.length) return true;
  return rows.every(row => Number.isFinite(Number(row.x)) && Number.isFinite(Number(row.y)));
}

function hasProtectiveDeviceSettings(project = {}) {
  const settings = project.tccSettings || project.settings?.tccSettings || {};
  if (Array.isArray(settings.devices) && settings.devices.length > 0) return true;
  if (settings.settings && typeof settings.settings === 'object' && Object.keys(settings.settings).length > 0) return true;
  const sheets = Array.isArray(project.oneLine?.sheets) ? project.oneLine.sheets : [];
  return sheets.some(sheet => meaningfulRecords(sheet.components).some(component => hasValue(component.tccId)));
}

function reviewedGateState(gate, approvals = {}) {
  const approval = approvals && typeof approvals === 'object' ? approvals[gate.id] : null;
  if (!approvalIsReviewed(approval)) {
    return { ...gate, status: 'open', approval: null };
  }
  return { ...gate, status: 'reviewed', approval };
}

export function normalizeDesignBasis(input = null) {
  const source = input && typeof input === 'object' ? input : {};
  const defaults = clone(DEFAULT_DESIGN_BASIS);
  const codeBasis = source.codeBasis || {};
  const sizingDefaults = source.sizingDefaults || {};
  const routingDefaults = source.routingDefaults || {};
  const studyPrerequisites = source.studyPrerequisites || {};
  const approvalRules = source.approvalRules || {};

  return {
    schemaVersion: 1,
    codeBasis: {
      primaryCode: choice(text(codeBasis.primaryCode, defaults.codeBasis.primaryCode), PRIMARY_CODES, defaults.codeBasis.primaryCode),
      edition: text(codeBasis.edition, defaults.codeBasis.edition),
      jurisdiction: text(codeBasis.jurisdiction),
      ahj: text(codeBasis.ahj),
      unitSystem: choice(text(codeBasis.unitSystem, defaults.codeBasis.unitSystem), UNIT_SYSTEMS, defaults.codeBasis.unitSystem)
    },
    sizingDefaults: {
      conductorMaterial: choice(text(sizingDefaults.conductorMaterial, defaults.sizingDefaults.conductorMaterial), CONDUCTOR_MATERIALS, defaults.sizingDefaults.conductorMaterial),
      insulationType: text(sizingDefaults.insulationType, defaults.sizingDefaults.insulationType),
      temperatureRatingC: choice(numberValue(sizingDefaults.temperatureRatingC, defaults.sizingDefaults.temperatureRatingC), TEMP_RATINGS, defaults.sizingDefaults.temperatureRatingC),
      installationType: choice(text(sizingDefaults.installationType, defaults.sizingDefaults.installationType), INSTALLATION_TYPES, defaults.sizingDefaults.installationType),
      defaultPowerFactor: numberValue(sizingDefaults.defaultPowerFactor, defaults.sizingDefaults.defaultPowerFactor, { min: 0.1, max: 1 }),
      voltageDropLimitPct: numberValue(sizingDefaults.voltageDropLimitPct, defaults.sizingDefaults.voltageDropLimitPct, { min: 0.1, max: 20 }),
      continuousLoadPolicy: choice(text(sizingDefaults.continuousLoadPolicy, defaults.sizingDefaults.continuousLoadPolicy), CONTINUOUS_POLICIES, defaults.sizingDefaults.continuousLoadPolicy)
    },
    routingDefaults: {
      defaultLengthFt: numberValue(routingDefaults.defaultLengthFt, defaults.routingDefaults.defaultLengthFt, { min: 1 }),
      defaultTrayId: text(routingDefaults.defaultTrayId, defaults.routingDefaults.defaultTrayId),
      defaultTrayWidthIn: numberValue(routingDefaults.defaultTrayWidthIn, defaults.routingDefaults.defaultTrayWidthIn, { min: 1 }),
      defaultTrayDepthIn: numberValue(routingDefaults.defaultTrayDepthIn, defaults.routingDefaults.defaultTrayDepthIn, { min: 1 }),
      defaultTrayElevationFt: numberValue(routingDefaults.defaultTrayElevationFt, defaults.routingDefaults.defaultTrayElevationFt),
      fillLimitPct: numberValue(routingDefaults.fillLimitPct, defaults.routingDefaults.fillLimitPct, { min: 1, max: 100 }),
      fieldRoutePolicy: choice(text(routingDefaults.fieldRoutePolicy, defaults.routingDefaults.fieldRoutePolicy), FIELD_ROUTE_POLICIES, defaults.routingDefaults.fieldRoutePolicy)
    },
    studyPrerequisites: {
      requireUtilityFault: boolValue(studyPrerequisites.requireUtilityFault, defaults.studyPrerequisites.requireUtilityFault),
      requireProtectiveDeviceSettings: boolValue(studyPrerequisites.requireProtectiveDeviceSettings, defaults.studyPrerequisites.requireProtectiveDeviceSettings),
      requireEquipmentCoordinates: boolValue(studyPrerequisites.requireEquipmentCoordinates, defaults.studyPrerequisites.requireEquipmentCoordinates),
      requireArcFlashInputs: boolValue(studyPrerequisites.requireArcFlashInputs, defaults.studyPrerequisites.requireArcFlashInputs)
    },
    approvalRules: {
      generatedRecordsRequireReview: boolValue(approvalRules.generatedRecordsRequireReview, defaults.approvalRules.generatedRecordsRequireReview),
      routeResultsRequireReview: boolValue(approvalRules.routeResultsRequireReview, defaults.approvalRules.routeResultsRequireReview),
      studiesRequireReview: boolValue(approvalRules.studiesRequireReview, defaults.approvalRules.studiesRequireReview),
      releaseRequiresReviewer: boolValue(approvalRules.releaseRequiresReviewer, defaults.approvalRules.releaseRequiresReviewer),
      reviewer: text(approvalRules.reviewer)
    },
    updatedAt: text(source.updatedAt)
  };
}

export function designBasisToAutomationOptions(input = null) {
  const basis = normalizeDesignBasis(input);
  return {
    designBasis: basis,
    defaultLengthFt: basis.routingDefaults.defaultLengthFt,
    defaultTrayId: basis.routingDefaults.defaultTrayId,
    defaultTrayWidthIn: basis.routingDefaults.defaultTrayWidthIn,
    defaultTrayDepthIn: basis.routingDefaults.defaultTrayDepthIn,
    defaultTrayElevationFt: basis.routingDefaults.defaultTrayElevationFt,
    conductorMaterial: basis.sizingDefaults.conductorMaterial,
    insulationType: basis.sizingDefaults.insulationType,
    tempRating: basis.sizingDefaults.temperatureRatingC,
    installationType: basis.sizingDefaults.installationType,
    defaultPowerFactor: basis.sizingDefaults.defaultPowerFactor,
    voltageDropLimitPct: basis.sizingDefaults.voltageDropLimitPct,
    continuousLoadPolicy: basis.sizingDefaults.continuousLoadPolicy,
    fieldRoutePolicy: basis.routingDefaults.fieldRoutePolicy,
    fillLimitPct: basis.routingDefaults.fillLimitPct
  };
}

export function summarizeDesignBasis(input = null) {
  const configured = input && typeof input === 'object';
  const basis = normalizeDesignBasis(input);
  const missing = [];
  const warnings = [];
  const reviewGates = [];

  if (!configured) {
    missing.push('Design Basis Wizard has not been saved.');
  }
  if (!hasValue(basis.codeBasis.primaryCode) || !hasValue(basis.codeBasis.edition)) {
    missing.push('Primary code and edition are required.');
  }
  if (!hasValue(basis.codeBasis.jurisdiction)) {
    warnings.push('Jurisdiction is blank.');
  }
  if (!hasValue(basis.codeBasis.ahj)) {
    warnings.push('Authority having jurisdiction is blank.');
  }
  if (basis.approvalRules.releaseRequiresReviewer && !hasValue(basis.approvalRules.reviewer)) {
    missing.push('Release approval reviewer is required by the approval rules.');
  }

  if (configured) {
    if (basis.studyPrerequisites.requireUtilityFault) {
      reviewGates.push('Utility/source fault duty must be confirmed before short-circuit, TCC, and arc-flash studies.');
    }
    if (basis.studyPrerequisites.requireProtectiveDeviceSettings) {
      reviewGates.push('Protective-device settings must be confirmed before TCC and arc-flash coordination.');
    }
    if (basis.studyPrerequisites.requireEquipmentCoordinates) {
      reviewGates.push('Equipment coordinates must be confirmed before routing and route-result deliverables.');
    }
    if (basis.studyPrerequisites.requireArcFlashInputs) {
      reviewGates.push('Arc-flash inputs and label assumptions must be reviewed before release.');
    }
    if (basis.approvalRules.generatedRecordsRequireReview) {
      reviewGates.push('Auto-generated equipment, one-line, cable, and raceway records require user review.');
    }
    if (basis.approvalRules.routeResultsRequireReview) {
      reviewGates.push('Auto-generated route results require routing review before field deliverables.');
    }
    if (basis.approvalRules.studiesRequireReview) {
      reviewGates.push('Saved study results require engineering review before report release.');
    }
  }

  const codeLabel = `${basis.codeBasis.primaryCode} ${basis.codeBasis.edition}`;
  const sizingLabel = `${basis.sizingDefaults.conductorMaterial === 'aluminum' ? 'Aluminum' : 'Copper'}, ${basis.sizingDefaults.temperatureRatingC}C, ${basis.sizingDefaults.insulationType}`;
  const routingLabel = `${basis.routingDefaults.defaultTrayId}, ${basis.routingDefaults.defaultTrayWidthIn} in x ${basis.routingDefaults.defaultTrayDepthIn} in, ${basis.routingDefaults.defaultLengthFt} ft default`;

  return {
    configured,
    complete: configured && missing.length === 0,
    basis,
    missing,
    warnings,
    reviewGates,
    codeLabel,
    sizingLabel,
    routingLabel
  };
}

export function buildDesignBasisReview(project = {}) {
  const summary = summarizeDesignBasis(project.designBasis || null);
  const approvals = project.designGateApprovals || project.reviewGateApprovals || {};
  const assumptions = [];
  const gates = [];
  const routeResults = routeResultRows(project.routeResults || project.latestRouteResults || project.settings?.latestRouteResults || []);
  const keysWithStudyResults = studyKeys(project.studies || project.settings?.studies || {});
  const generatedRecordCount = countGeneratedRecords(project);

  const addAssumption = (id, label, detail, source = 'design-basis') => {
    assumptions.push({ id, label, detail, source });
  };
  const addGate = (id, severity, label, detail, href, options = {}) => {
    gates.push(reviewedGateState({
      id,
      severity,
      label,
      detail,
      href,
      category: options.category || 'Design Basis',
      blocking: Boolean(options.blocking),
      reviewable: options.reviewable !== false,
      enforceOnDeliverables: Boolean(options.enforceOnDeliverables)
    }, approvals));
  };

  addAssumption('code-basis', 'Code basis', summary.configured ? summary.codeLabel : 'Default NEC 2023 until the wizard is saved.');
  addAssumption('sizing-defaults', 'Sizing defaults', summary.sizingLabel);
  addAssumption('routing-defaults', 'Routing defaults', summary.routingLabel);
  if (generatedRecordCount > 0) {
    addAssumption('generated-records', 'Auto-Build records', `${generatedRecordCount} generated or auto-assigned workflow record(s) are present.`);
  }
  if (routeResults.length > 0) {
    addAssumption('route-results', 'Route results', `${routeResults.length} route result row(s) are available for deliverables.`);
  }

  if (!summary.configured) {
    addGate(
      'design-basis-missing',
      'critical',
      'Save Design Basis Wizard',
      'Project defaults, study prerequisites, and release approval rules have not been saved.',
      'workflowdashboard.html',
      { blocking: true, enforceOnDeliverables: true, reviewable: false }
    );
  }

  summary.missing.forEach((detail, index) => {
    addGate(
      `design-basis-missing-${index + 1}`,
      'critical',
      'Complete design basis',
      detail,
      'workflowdashboard.html',
      { blocking: true, enforceOnDeliverables: true, reviewable: false }
    );
  });

  summary.warnings.forEach((detail, index) => {
    addGate(
      `design-basis-warning-${index + 1}`,
      'warning',
      'Review design basis note',
      detail,
      'workflowdashboard.html',
      { reviewable: true }
    );
  });

  const { basis } = summary;
  if (summary.configured) {
    if (basis.studyPrerequisites.requireUtilityFault && !studyHasResults((project.studies || project.settings?.studies || {}).shortCircuit)) {
      addGate(
        'utility-fault-duty',
        'warning',
        'Confirm utility/source fault duty',
        'Short-circuit or source fault duty results are required before relying on TCC, arc-flash, and coordination deliverables.',
        'shortCircuit.html',
        { blocking: true, enforceOnDeliverables: true }
      );
    }
    if (basis.studyPrerequisites.requireProtectiveDeviceSettings && !hasProtectiveDeviceSettings(project)) {
      addGate(
        'protective-device-settings',
        'warning',
        'Confirm protective-device settings',
        'TCC device assignments or protective-device setting data are required before coordination and arc-flash release.',
        'tcc.html',
        { blocking: true, enforceOnDeliverables: true }
      );
    }
    if (basis.studyPrerequisites.requireEquipmentCoordinates && !hasEquipmentCoordinates(project.equipment || [])) {
      addGate(
        'equipment-coordinates',
        'warning',
        'Confirm equipment coordinates',
        'Equipment rows need X/Y coordinates before route results, pull cards, and routing deliverables can be treated as reviewed.',
        'equipmentlist.html',
        { blocking: true, enforceOnDeliverables: true }
      );
    }
    if (basis.studyPrerequisites.requireArcFlashInputs && !studyHasResults((project.studies || project.settings?.studies || {}).arcFlash)) {
      addGate(
        'arc-flash-inputs',
        'warning',
        'Review arc-flash inputs',
        'Arc-flash inputs and label assumptions must be reviewed before issuing release deliverables.',
        'arcFlash.html',
        { blocking: true, enforceOnDeliverables: true }
      );
    }
    if (basis.approvalRules.generatedRecordsRequireReview && generatedRecordCount > 0) {
      addGate(
        'generated-record-review',
        'warning',
        'Review Auto-Build records',
        `${generatedRecordCount} generated or auto-assigned record(s) need user review before they are treated as design basis.`,
        'workflowdashboard.html',
        { blocking: false, enforceOnDeliverables: true }
      );
    }
    if (basis.approvalRules.routeResultsRequireReview && routeResults.length > 0) {
      addGate(
        'route-result-review',
        'warning',
        'Review route results',
        `${routeResults.length} route result row(s) should be reviewed before pull-card, spool, or report release.`,
        'optimalRoute.html',
        { blocking: false, enforceOnDeliverables: true }
      );
    }
    if (basis.approvalRules.studiesRequireReview && keysWithStudyResults.length > 0) {
      const approvalsByStudy = project.studyApprovals || project.approvals || project.settings?.studyApprovals || {};
      const unreviewed = keysWithStudyResults.filter(key => !approvalIsReviewed(approvalsByStudy[key]));
      if (unreviewed.length > 0) {
        addGate(
          'study-result-review',
          'warning',
          'Review saved study results',
          `${unreviewed.length} saved study result(s) need an approval record: ${unreviewed.join(', ')}.`,
          'demandschedule.html',
          { blocking: false, enforceOnDeliverables: true }
        );
      }
    }
  }

  const openGates = gates.filter(gate => gate.status !== 'reviewed');
  const deliverableBlockers = openGates.filter(gate => gate.enforceOnDeliverables);

  return {
    summary,
    assumptions,
    gates,
    openGates,
    openGateCount: openGates.length,
    blockingGateCount: openGates.filter(gate => gate.blocking || gate.severity === 'critical').length,
    deliverableBlockers,
    readyForDeliverables: deliverableBlockers.length === 0
  };
}
