name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Lint JavaScript
        run: npx eslint "**/*.js"
      - name: Lint HTML
        run: npx htmlhint "**/*.html"
      - name: Run unit tests
        run: node test.js
      - name: Check documentation links
        run: |
          npx markdown-link-check README.md
          npx markdown-link-check docs/*.md
